In [1]:
import pandas as pd
import re
import nltk
nltk.download('popular')
from nltk.tokenize import word_tokenize
from nltk import pos_tag
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('wordnet')
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
nltk.download('sentiwordnet')
from nltk.corpus import sentiwordnet as swn

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection popular
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package sentiwordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/sentiwordnet.zip.

In [2]:
raw_bottom = pd.read_csv("bottom_movie_reviews.csv")
raw_top = pd.read_csv("top_movie_reviews.csv")

In [3]:
raw_top

,user_name,title,rating,date,review
0,NaN,"An offer so good, I couldn't refuse",10,1 April 2019,It is now past 1 PM and I just finished watchi...
1,NaN,"For Me, This Is The Definitive Film",10,11 February 2018,This isn't just a beautifully crafted gangster...
2,NaN,One of the best of all time.,10,6 February 2021,"A masterclass in film making, is The Godfather..."
3,NaN,An Iconic Film,10,21 June 2008,Tell me a movie that is more famous than this....
4,NaN,"Another kind of ""family movie""",10,5 March 2002,The Godfather is one of the few films in which...
...,...,...,...,...,...
8108,NaN,Stop! Bad dates...,10,17 August 2021,This is a perfect movie. It is filled with as ...
8109,NaN,Lunatic and Fraud.,2,10 September 1998,What's this - 2 Speilberg films in the top 10...
8110,NaN,Harrison Ford stole the show,7,2 June 2022,"""Oh, my God, this whole place is slithering""I'..."
8111,NaN,Adventure movies are always fun and engaging,9,20 March 2020,"In the first-generation adventure film, everyo..."
8112,NaN,American arrogance as entertainment product,3,7 March 2021,An American archeologist goes to Egypt to stea...

In [4]:
raw_bottom

,user_name,title,rating,date,review
0,NaN,"The fact that aspiring actors, directors, and ...",1,28 August 2008,*Disclaimer: I only watched this movie as a co...
1,NaN,I'd thought I'd never see the day when I'd see...,1,7 September 2009,"Disaster Movie gets my vote as the ""new"" worst..."
2,NaN,Someone please put an end to Seltzer's awful c...,1,28 August 2008,I was given a free ticket to this film; so I c...
3,NaN,Never has a movie had a More Appropriate Title!,1,20 September 2013,Having seen the Scary Movie Series and many of...
4,NaN,Haven't we seen this sort of film 1479 times a...,1,16 January 2010,This film begins in 100001 BC and we see a cav...
...,...,...,...,...,...
6057,NaN,A movie of rich depth,2,10 November 2010,"So, if you're actually planning on watching th..."
6058,NaN,So painfully bad that it's actually amusing.,4,19 March 2007,"""Troll 2"" is an experience.The acting is ridic..."
6059,NaN,Cinematic masterpiece,10,4 March 2019,I don't understand why people hate on this mov...
6060,NaN,Atrocious,2,19 November 2006,This is one incredibly pathetic mess of a movi...
6061,NaN,Ride the tiger something something stripes are...,10,20 March 2022,Sometimes when I watch Troll 2 it's better to ...

In [5]:
raw_data = pd.concat([raw_top, raw_bottom], ignore_index=True)

In [6]:
raw_data

,user_name,title,rating,date,review
0,NaN,"An offer so good, I couldn't refuse",10,1 April 2019,It is now past 1 PM and I just finished watchi...
1,NaN,"For Me, This Is The Definitive Film",10,11 February 2018,This isn't just a beautifully crafted gangster...
2,NaN,One of the best of all time.,10,6 February 2021,"A masterclass in film making, is The Godfather..."
3,NaN,An Iconic Film,10,21 June 2008,Tell me a movie that is more famous than this....
4,NaN,"Another kind of ""family movie""",10,5 March 2002,The Godfather is one of the few films in which...
...,...,...,...,...,...
14170,NaN,A movie of rich depth,2,10 November 2010,"So, if you're actually planning on watching th..."
14171,NaN,So painfully bad that it's actually amusing.,4,19 March 2007,"""Troll 2"" is an experience.The acting is ridic..."
14172,NaN,Cinematic masterpiece,10,4 March 2019,I don't understand why people hate on this mov...
14173,NaN,Atrocious,2,19 November 2006,This is one incredibly pathetic mess of a movi...
14174,NaN,Ride the tiger something something stripes are...,10,20 March 2022,Sometimes when I watch Troll 2 it's better to ...

In [7]:
raw_data = raw_data[["review"]]
raw_data

                                                  review
0      It is now past 1 PM and I just finished watchi...
1      This isn't just a beautifully crafted gangster...
2      A masterclass in film making, is The Godfather...
3      Tell me a movie that is more famous than this....
4      The Godfather is one of the few films in which...
...                                                  ...
14170  So, if you're actually planning on watching th...
14171  "Troll 2" is an experience.The acting is ridic...
14172  I don't understand why people hate on this mov...
14173  This is one incredibly pathetic mess of a movi...
14174  Sometimes when I watch Troll 2 it's better to ...

[14175 rows x 1 columns]

In [8]:
sentences_data = []
for index, row in raw_data.iterrows():
    review = row['review']
    separated_sentences = nltk.sent_tokenize(review)
    sentences_data.extend(separated_sentences)
data = pd.DataFrame({"review": sentences_data})

In [9]:
data

                                                   review
0       It is now past 1 PM and I just finished watchi...
1                            I should probably go to bed.
2       It's late and tomorrow I have to wake up a bit...
3       But not early enough to postpone writing these...
4       Now that I have seen it three times, the oppor...
...                                                   ...
183651  There is no way to make this movie on purpose ...
183652                     2 out of 3 found this helpful.
183653                           Was this review helpful?
183654                                   Sign in to vote.
183655                                          Permalink

[183656 rows x 1 columns]

In [10]:
def clean_text(text):
    text = re.sub('[^A-Za-z]+', ' ', text)
    return text

In [11]:
data['cleaned_review'] = data['review'].apply(clean_text)
data.head()

,review,cleaned_review
0,It is now past 1 PM and I just finished watchi...,It is now past PM and I just finished watching...
1,I should probably go to bed.,I should probably go to bed
2,It's late and tomorrow I have to wake up a bit...,It s late and tomorrow I have to wake up a bit...
3,But not early enough to postpone writing these...,But not early enough to postpone writing these...
4,"Now that I have seen it three times, the oppor...",Now that I have seen it three times the opport...

In [12]:
pos_dict = {'J':wordnet.ADJ, 'V':wordnet.VERB, 'N':wordnet.NOUN, 'R':wordnet.ADV}
def token_stop_pos(text):
  tags = pos_tag(word_tokenize(text))
  newlist = []
  for word, tag in tags:
      if word.lower() not in set(stopwords.words('english')):
        newlist.append(tuple([word, pos_dict.get(tag[0])]))
  return newlist

In [13]:
data['pos_tagged'] = data['cleaned_review'].apply(token_stop_pos)
data.head()

,review,cleaned_review,pos_tagged
0,It is now past 1 PM and I just finished watchi...,It is now past PM and I just finished watching...,"[(past, a), (PM, n), (finished, v), (watching,..."
1,I should probably go to bed.,I should probably go to bed,"[(probably, r), (go, v), (bed, v)]"
2,It's late and tomorrow I have to wake up a bit...,It s late and tomorrow I have to wake up a bit...,"[(late, a), (tomorrow, n), (wake, v), (bit, r)..."
3,But not early enough to postpone writing these...,But not early enough to postpone writing these...,"[(early, r), (enough, r), (postpone, v), (writ..."
4,"Now that I have seen it three times, the oppor...",Now that I have seen it three times the opport...,"[(seen, v), (three, None), (times, v), (opport..."

In [14]:
wordnet_lemmatizer = WordNetLemmatizer()
def lemmatize(pos_data):
  lemma_rew = " "
  for word, pos in pos_data:
    if not pos:
        lemma = word
        lemma_rew = lemma_rew + " " + lemma
    else:
        lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
        lemma_rew = lemma_rew + " " + lemma
  return lemma_rew

In [15]:
data['lemma'] = data['pos_tagged'].apply(lemmatize)
data.head()

,review,cleaned_review,pos_tagged,lemma
0,It is now past 1 PM and I just finished watchi...,It is now past PM and I just finished watching...,"[(past, a), (PM, n), (finished, v), (watching,...",past PM finish watch Francis Ford Coppola Go...
1,I should probably go to bed.,I should probably go to bed,"[(probably, r), (go, v), (bed, v)]",probably go bed
2,It's late and tomorrow I have to wake up a bit...,It s late and tomorrow I have to wake up a bit...,"[(late, a), (tomorrow, n), (wake, v), (bit, r)...",late tomorrow wake bit early
3,But not early enough to postpone writing these...,But not early enough to postpone writing these...,"[(early, r), (enough, r), (postpone, v), (writ...",early enough postpone write line
4,"Now that I have seen it three times, the oppor...",Now that I have seen it three times the opport...,"[(seen, v), (three, None), (times, v), (opport...",see three time opportunity share thought ref...

In [16]:
def sentiwordnetanalysis(pos_data):
  sentiment = 0
  tokens_count = 0
  for word, pos in pos_data:
      if not pos:
          continue
      lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
      if not lemma:
          continue
      synsets = wordnet.synsets(lemma, pos=pos)
      if not synsets:
          continue
      # Take the first sense, the most common
      synset = synsets[0]
      swn_synset = swn.senti_synset(synset.name())
      sentiment += swn_synset.pos_score() - swn_synset.neg_score()
      tokens_count += 1
      # print(swn_synset.pos_score(),swn_synset.neg_score(),swn_synset.obj_score())
  if not tokens_count:
      return None
  if sentiment>0:
      return "positive"
  if sentiment==0:
      return "neutral"
  else:
      return "negative"

In [17]:
data['polarity'] = data['pos_tagged'].apply(sentiwordnetanalysis)
data.head()

,review,cleaned_review,pos_tagged,lemma,polarity
0,It is now past 1 PM and I just finished watchi...,It is now past PM and I just finished watching...,"[(past, a), (PM, n), (finished, v), (watching,...",past PM finish watch Francis Ford Coppola Go...,negative
1,I should probably go to bed.,I should probably go to bed,"[(probably, r), (go, v), (bed, v)]",probably go bed,neutral
2,It's late and tomorrow I have to wake up a bit...,It s late and tomorrow I have to wake up a bit...,"[(late, a), (tomorrow, n), (wake, v), (bit, r)...",late tomorrow wake bit early,neutral
3,But not early enough to postpone writing these...,But not early enough to postpone writing these...,"[(early, r), (enough, r), (postpone, v), (writ...",early enough postpone write line,positive
4,"Now that I have seen it three times, the oppor...",Now that I have seen it three times the opport...,"[(seen, v), (three, None), (times, v), (opport...",see three time opportunity share thought ref...,positive

In [18]:
data.count()

review            183656
cleaned_review    183656
pos_tagged        183656
lemma             183656
polarity          174046
dtype: int64

In [19]:
data['polarity'].value_counts()

positive    87452
negative    49704
neutral     36890
Name: polarity, dtype: int64

In [20]:
data.to_csv('labeled_data.csv',index=False)

https://www.analyticsvidhya.com/blog/2021/06/rule-based-sentiment-analysis-in-python/#:~:text=This%20is%20a%20practical%20approach,is%20called%20Lexicon%20based%20approach.